site_name: Juicedocs
nav:
  - "ğŸ‘‹ Welcome": "index.md"
  - "ğŸŒ± Getting Started":
      - Creating a Juicebox Project: "getting-started/creating.md"
      - Configuring your Project: "getting-started/configuring.md"
  - "ğŸ“š Key Concepts":
      - "concepts/understanding-funding-cycles.md"
      - "concepts/understanding-overflow.md"
      - "concepts/understanding-tokens.md"
  - "ğŸ‘¾ Protocol v2":
      - "ğŸ‘¾ Protocol v2": "protocol-v2/index.md"
  - "â˜ ï¸ Protocol v1 (deprecated)":
      - "TODO.md"
  - "ğŸ‘©â€ğŸ’» Developers":
      - "Contract Addresses": "developers/contract-addresses.md"
      - "Integration Guide": "developers/integration-guide.md"
      - "Subgraph": "developers/subgraph.md"
  - "ğŸ™Œ Hiring":
      - "hiring/join-the-team.md"
  - "ğŸ”— Links":
      - "Juicebox.money": "http://juicebox.money"
      - "GitHub": "https://github.com/jbx-protocol"
      - "Twitter": "https://twitter.com/juiceboxETH"
      - "Discord": "https://discord.gg/5JsDvuyCPd"
theme: material
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
